### PR TITLE
Update turletters.py

### PR DESCRIPTION
**Pull request by KvngTre**

### CODE REVIEW

**Comment by KvngTre** [comment]
Python Turtles - how big box?
import turtle

window = turtle.Screen()
me = turtle.Turtle()

me.forward(100)
me.left(90)
me.forward(100)
me.left(90)
me.forward(100)
me.left(90)
me.forward(100)

**Comment by KvngTre** [comment]
Errors

What is a syntax error?

a character or string incorrectly placed in a command or instruction that
causes a failure in execution.
Question #
2

What is a semantic (logical) error?

A *semantic error* is one related to the meaning of something. For example,
a syntactically perfect statement made in the wrong context is a *semantic
error* which may be detected at compile-time. ... A *logic error* is one
that refers to an incorrect program *logic*.
Question #
3

What is a runtime error?
*Runtime Error* is an *error* that occurs during execution of a program. It
is a software or hardware problem that deters a program from working
correctly. *Run-time* errors might cause you to lose information in the
file you're working upon

**Comment by bedavis** [comment]
Got it.

**Comment by bedavis** [comment]
Python errors, got it.

**Pull request merged**
